logging:
  version: 1

  disable_existing_loggers: false

  formatters:
    default:
      format: '%(asctime)s - %(levelname)-6s - %(name)25s - %(message)s'
      datefmt: '%Y-%m-%dT%H:%M:%S'

    color:
      class: colorlog.ColoredFormatter
      format: '%(asctime)s %(log_color)s%(levelname)-6s%(reset)s %(blue)s%(name)30s%(reset)s: %(message)s'
      datefmt: '%Y-%m-%dT%H:%M:%S'

  handlers:
    colorized_stdout:
      class: logging.StreamHandler
      formatter: color
      stream: ext://sys.stdout
      level: DEBUG

    stdout:
      class: logging.StreamHandler
      formatter: default
      stream: ext://sys.stdout

  loggers:
    asyncio:
      level: ERROR
    connexion:
      level: INFO
    docker:
      level: INFO
    elastic_transport:
      level: ERROR
    testcontainers:
      level: ERROR
    urllib3:
      level: ERROR
