name: Build Python package and publish to PyPi

on:
  workflow_call:
    secrets:
      actor_token:
        description: |
          GITHUB_TOKEN or PAT authorized to make changes to the repository
        required: true

jobs:
  ref-prerequisites:
    uses: ./.github/workflows/.prerequisites.yml

  ref-check-repo-settings:
    uses: kerrys-learning-lab/.github/.github/workflows/.check-repo-settings.yml@main
    secrets:
      actor_token: ${{ secrets.actor_token }}

  ref-python-package-pypi:
    uses: ./.github/workflows/.python-package-pypi.yml
    with:
      publish: startsWith( github.ref, 'refs/tags/v')
    secrets:
      actor_token: ${{ secrets.KERRYS_LEARNING_LAB_TOKEN }}

  ref-bump-version:
    uses: kerrys-learning-lab/.github/.github/workflows/.bump-version.yml@main
    needs:
      - ref-check-repo-settings
      - ref-python-package-pypi
    secrets:
      actor_name: ${{ secrets.actor_name }}
      actor_token: ${{ secrets.actor_token }}
      actor_email: ${{ secrets.actor_email }}
