name: Build Python package and publish to PyPi

on: [push, workflow_dispatch]

jobs:

  ref-python-package-pypi:
    uses: ./.github/workflows/python-package-pypi.workflow.yml
    with:
      publish: ${{ startsWith( github.ref, 'refs/tags/v') || inputs.publish }}
    secrets:
      actor_token: ${{ secrets.KERRYS_LEARNING_LAB_TOKEN }}
