name: Build Python package and publish to PyPi

on: [push, workflow_dispatch]

jobs:

  ref-python-package-pypi:
    uses: ./.github/workflows/python-package-pypi.workflow.yml
    with:
      publish: ${{ startsWith( github.ref, 'refs/tags/v') }}
    secrets:
      actor_name: ${{ secrets.KERRYS_LEARNING_LAB_ACTOR }}
      actor_token: ${{ secrets.KERRYS_LEARNING_LAB_TOKEN }}
      actor_email: ${{ secrets.KERRYS_LEARNING_LAB_EMAIL }}
